<Project Sdk="Microsoft.NET.Sdk">

	
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Authors>Smelov</Authors>
		<Company>Smelov</Company>
		<Description>Results collection service</Description>
		<PackageId>BSTU.Results.Collection</PackageId>
		<Version>2.0.0</Version>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

</Project>
