alter pluggable database KNP_PDB open;
alter session set container=KNP_PDB;
show con_name;

create tablespace TS_KNP
  DATAFILE 'TS_KNP_LAB7_PDB.dbf'
  size 7M
  autoextend ON
  next 5M
  maxsize 20M;

create temporary tablespace TS_KNP_TEMP
  tempfile 'TS_KNP_TEMP_LAB7_PDB.dbf'
  size 5M
  autoextend ON
  next 3M
  maxsize 30M;

select TABLESPACE_NAME, STATUS, contents logging from SYS.DBA_TABLESPACES;
drop tablespace TS_KNP including contents and datafiles;
drop tablespace TS_KNP_TEMP including contents and datafiles;

CREATE PROFILE PF_KNP LIMIT
  FAILED_LOGIN_ATTEMPTS 7
  SESSIONS_PER_USER 3
  PASSWORD_LIFE_TIME 600
  PASSWORD_REUSE_TIME 3650
  PASSWORD_LOCK_TIME 1
  CONNECT_TIME 1800;

select * from DBA_PROFILES where profile = 'PF_KNP';
drop profile PF_KNP;


CREATE USER KNP identified by 111
  DEFAULT TABLESPACE TS_KNP
  TEMPORARY TABLESPACE TS_KNP_TEMP
  PROFILE PF_KNP
  ACCOUNT UNLOCK;

select * from dba_users where USERNAME like 'KNP';
drop user KNP;

GRANT CREATE SESSION TO KNP;
GRANT RESTRICTED SESSION TO KNP;
GRANT CREATE ANY TABLE TO KNP;
GRANT CREATE ANY VIEW TO KNP;
GRANT CREATE ANY PROCEDURE TO KNP;
GRANT EXECUTE ANY PROCEDURE TO KNP;
GRANT DROP ANY PROCEDURE TO KNP;
GRANT CREATE SEQUENCE TO KNP;
GRANT UNLIMITED TABLESPACE TO KNP;
GRANT CREATE CLUSTER TO KNP;
GRANT CREATE SYNONYM TO KNP;
GRANT CREATE PUBLIC SYNONYM TO KNP;
GRANT CREATE MATERIALIZED VIEW TO KNP;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'KNP';

-- 1.


-- 2.
create sequence S1
  start with 1000
  increment by 10
  nominvalue
  nomaxvalue
  nocycle
  nocache
  noorder;

select S1.NEXTVAL from DUAL;
select S1.CURRVAL from DUAL;

-- 3.
create sequence S2
  start with 10
  increment by 10
  maxvalue 100
  nocycle;

select S2.NEXTVAL from DUAL;


-- 5.
create sequence S3
  start with 10
  increment by -10
  minvalue -100
  maxvalue 100
  nocycle
  order;

select S3.NEXTVAL from DUAL;

-- 6.

create sequence S4
  start with 1
  increment by 1
  maxvalue 10
  cycle
  cache 5
  noorder;

select S4.NEXTVAL from DUAL;

-- 7.
SELECT * FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER = 'KNP';
DROP SEQUENCE S1;
DROP SEQUENCE S2;
DROP SEQUENCE S3;
DROP SEQUENCE S4;

-- 8.
CREATE TABLE T1 (
  N1 NUMBER(20),
  N2 NUMBER(20),
  N3 NUMBER(20),
  N4 NUMBER(20)
) CACHE STORAGE ( BUFFER_POOL KEEP ) tablespace TS_KNP;

BEGIN
  FOR i IN 1..7 LOOP
    INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
  END LOOP;
END;

SELECT * FROM T1;


-- 9.
CREATE CLUSTER ABC (
  X NUMBER(10),
  V VARCHAR2(12)
) SIZE 200 HASHKEYS 200;

-- 10.
CREATE TABLE A (
  XA NUMBER(10),
  VA VARCHAR2(12),
  Y NUMBER(10)
) CLUSTER ABC(XA, VA);

-- 11.
CREATE TABLE B (
  XB NUMBER(10),
  VB VARCHAR2(12),
  Z NUMBER(10)
) CLUSTER ABC(XB, VB);

INSERT INTO B VALUES (1, '1', 1);

-- 12.
CREATE TABLE C (
  XC NUMBER(10),
  VC VARCHAR2(12),
  W NUMBER(10)
) CLUSTER ABC(XC, VC);

INSERT INTO C VALUES (1, '1', 1);

-- 13.
SELECT TABLE_NAME FROM USER_TABLES;
SELECT CLUSTER_NAME FROM USER_CLUSTERS;

-- 14.
CREATE SYNONYM SC FOR KNP.C;
SELECT * FROM C;
SELECT * FROM SC;

-- 15.
CREATE PUBLIC SYNONYM SB FOR KNP.B;
SELECT * FROM SB;


-- 16.
CREATE TABLE A16 (
  XA NUMBER(10),
  VA VARCHAR2(12),
  Y NUMBER(10),
  CONSTRAINT PK_A16 PRIMARY KEY (XA)
);

CREATE TABLE B16 (
  XB NUMBER(10),
  VB VARCHAR2(12),
  Z NUMBER(10),
  CONSTRAINT FK_B16 FOREIGN KEY (XB) REFERENCES A16(XA)
);

INSERT INTO A16 VALUES (1, '1', 1);
INSERT INTO B16 VALUES (1, '1', 1);
INSERT INTO B16 VALUES (1, '26', 33);

CREATE VIEW V1 AS
  SELECT * FROM A16
  INNER JOIN B16 ON A16.XA = B16.XB;

SELECT * FROM V1;

-- 17.
DROP MATERIALIZED VIEW MV;

CREATE MATERIALIZED VIEW MV
REFRESH FORCE
START WITH SYSDATE
NEXT SYSDATE + 2/1440
  AS
    select * from A16
    inner join
    B16
    on A16.XA = B16.XB;

select * from mv;

EXEC DBMS_MVIEW.REFRESH('MV');

-- ?????? ??? ????????
DROP MATERIALIZED VIEW MV;
DROP VIEW V1;
DROP PUBLIC SYNONYM SB;
DROP SYNONYM SC;
DROP TABLE B16 CASCADE CONSTRAINTS;
DROP TABLE A16 CASCADE CONSTRAINTS;
DROP TABLE A CASCADE CONSTRAINTS;
DROP TABLE B CASCADE CONSTRAINTS;
DROP TABLE C CASCADE CONSTRAINTS;
DROP CLUSTER ABC INCLUDING TABLES CASCADE CONSTRAINTS;